export const SET_GAME_STARTED = "SET_GAME_STARTED";
export const SET_INSTRUCTION_EXPANDED = "SET_INSTRUCTION_EXPANDED";

export const DECK = {
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR"
}

export const DECK_DRAW = {
    FETCH_SUCCESS: "DECK_DRAW_FETCH_SUCCESS",
    FETCH_ERROR: "DECK_DRAW_FETCH_ERROR"
}